title: Danito
permalink: /blog/:year/:month/:day/:title
pygments: true
exclude:
  README.md

maruku:
  use_tex:      false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
