title: Daniel Foguel
permalink: /blog/:year/:month/:day/:title
pygments: True
markdown: maruku
paginate: 4
exclude:
  README.md

maruku:
  use_tex:      false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
